// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://druphgctbmfgbkpgvjhs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRydXBoZ2N0Ym1mZ2JrcGd2amhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0NDI5MzcsImV4cCI6MjA1ODAxODkzN30.h1HYCzOy41jj6kLlK10nbTiFtbnkhovCG3AJ-v8fLws";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);